### ISSUE TITLE
Content review feedback

### ISSUE THREAD

**Issue by evelinec** [OpenLiberty/draft-guide-springboot-mvc#6] opened 2018-06-26 21:41 UTC
- [x] The use of words, ie, "this guide" and "that guide" can be reworded. ie, "The starting point of this guide will be the finished application..." and "Please first go through that guide if you are not familiar..."

- [x] I think generally "Note that.." in "Note that Java 8 is required to run this project." is not ID standard. Also not sure mentioning Java 8 requirement is needed in the intro.

- [x] Note that this guide will not cover migration of test cases, and the starting project does not include test code or dependencies. => I think this can be mention in the test section of the guide instead of in the intro. 

- [x] Within "What you'll learn", may be good to add what's the benefit of using Open Liberty or explain why using OL. 

- [x] The repo to be name same as the projectid, or vice versa. 

- [x] "You’ll see from the page output that the GreetingController handled the name request parameter:" => is it possible not to refer to "GreetingController" directly here? It's the first time it's being mentioned in the guide, if you have to mention it, may be good to add some explanation about it.  Can't expect all users actually go through the spring guide to learn about the controller. 

- [x] Running the starting application in embedded Tomcat => I think the word "starting" is not needed.

- [x] Navigate to the start/pom.xml file to modify the starter POM. => Since there's a mention of the changes are to be done within the `start` folder, there's no need to refer to the pom.xml with the `start\` directory anymore.

- [x] Under "Migrating the application", in general, we don't ask user to insert line of code in a file anymore. Refer to this wiki for structuring and styling the guide: https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles. You can also check out this guide as an example: https://github.com/OpenLiberty/guide-cdi-intro. In short, the instruction should ask user to create the pom.xml file, and then refer to the line(s) of code that you would like to talk about. 

- [x] The intro describes 4 steps to do the migration, but looks like there're 3.

- [x] "Change the packaging type", "Add POM properties", "Add and modify dependencies" and "Add the Liberty Maven Plugin" sub headings may not be needed. Can be replaced with a sentence. ie, perhaps "First, you need to change the package to `<packaging>liberty-assembly</packaging>`."

- [x] The related guide section is linked to an empty guide.

**Comment by yeekangc** [comment] 2018-06-28 14:28
Generally speaking, we won't use "please".  For point 1 and 2 and changes there, we can consult @sishida where and if necessary.

**Comment by sishida** [comment] 2018-06-28 14:45
It's best not to use self-referential language, such as "this guide," at all if we can avoid it. It's better if we could say, "Start with the finished application..." or "If you're not familiar with *name of concept*, complete *name of guide with link*..."

The issue with words like "Note that" and "please" is that they're just not really necessary. The "pleases" would overrun the doc if we included them in front of every command we gave. :)

**Comment by chyt** [comment] 2018-07-05 12:50
> The use of words, ie, "this guide" and "that guide" can be reworded. ie, "The starting point of this guide will be the finished application..." and "Please first go through that guide if you are not familiar..."

> It's best not to use self-referential language, such as "this guide," at all if we can avoid it. It's better if we could say, "Start with the finished application..." or "If you're not familiar with , complete ..."

@sishida Can you explain the benefit of doing this? From the examples that you gave, it just comes off as sounding intentionally vague. The second example you gave isn't grammatically accurate; what are you not familiar with? I don't see the problem with referencing the guide in the third person (the same way you would reference a person's name as "he" or "she").

**Comment by sishida** [comment] 2018-07-05 13:17
@chyt Hi! I edited the original comment so that you can now see the whole statement as intended. It had been hidden before because the words that are now in italics were originally in angled brackets. Sorry about that--I forgot about GitHub's way of automatically formatting content!

Self-referential language is sort of redundant/unnecessary because the user should assume that the contents of the guide they're reading apply to that guide. For example, I wouldn't say, "This book is a story about..." or "In this story...". Rather, I'd just start writing about what happens in the story. The reader should already know it's a story (about something). Same thing with instructions. You can just jump right in and start telling the user what to do instead of first telling them that they're looking at a guide and that these particular instructions concern this particular guide. Hope that helps! :)

**Comment by chyt** [comment] 2018-07-05 13:30
> I think generally "Note that.." in "Note that Java 8 is required to run this project." is not ID standard. Also not sure mentioning Java 8 requirement is needed in the intro.

What does ID standard mean? Also why would you not mention this in the intro? If the user is running an older version they are told upfront that the guide will not work for them. If they cannot or aren't willing to upgrade to a later version, then they aren't wasting any more time reading additional content that won't be useful to them. 

> Note that this guide will not cover migration of test cases, and the starting project does not include test code or dependencies. => I think this can be mention in the test section of the guide instead of in the intro.

Again, I think that you want to be upfront with the reader. After I state that the migration is taking place on an existing Spring Boot application, and to go through the guide for that application first, they will naturally expect that the entirety of that application is migrated. I think it is important that the `What you'll learn` section also addresses what the reader will not learn, if they expect to learn that based on the context. 

Also, what is the alternative? It doesn't make sense to create a test section in the guide just to tell them that we won't be covering test migration. That's why I deleted the section to begin with. 

> "You’ll see from the page output that the GreetingController handled the name request parameter:" => is it possible not to refer to "GreetingController" directly here? It's the first time it's being mentioned in the guide, if you have to mention it, may be good to add some explanation about it. Can't expect all users actually go through the spring guide to learn about the controller.

I could say something like `a controller (specifically GreetingController)`. However, I'm not sure how useful this is as the class name is self-explanatory. The reader will either be already familiar with the MVC paradigm (in which case they would not be surprised that some controller class is handling the request), or they are not (in which case they should have gone through the Spring guide). But why would they be interested in migrating a Spring MVC application if they are not familiar with Spring MVC to begin with?

> Navigate to the start/pom.xml file to modify the starter POM. => Since there's a mention of the changes are to be done within the start folder, there's no need to refer to the pom.xml with the start\ directory anymore.

I agree. However I was given feedback in #3 that it was to be added. I think that the entire sentence is unnecessary. The reader already knows that we are modifying files in the `start` folder, and the title of the section is `Modifying the pom`. There is reasonably only one file that I could be referring to. Please clarify. 

> Under "Migrating the application", in general, we don't ask user to insert line of code in a file anymore. Refer to this wiki for structuring and styling the guide: https://github.com/OpenLiberty/draft-guides-template/wiki/Guidelines-for-Structure-and-Styles. You can also check out this guide as an example: https://github.com/OpenLiberty/guide-cdi-intro. In short, the instruction should ask user to create the pom.xml file, and then refer to the line(s) of code that you would like to talk about.

While this may be the general format, I disagree that doing this is the best way to present an application migration. Presenting the whole file as a new one might be fine when most/all of the initial code is just boilerplate. However, for an application migration the majority of code is already written, and the user is more interested in the specific changes that are necessary for migration. These are the ones that they will be applying in their own migrations and the rest of the code is application-specific. Telling them to create a new file doesn't sound like they're performing a migration anymore. 

For the multi-pane format, I think it is appropriate to just display the entirety of the finished file on the right, but still keep the code snippets and reference the corresponding line numbers in the finished file. 

> The intro describes 4 steps to do the migration, but looks like there're 3.

I agree that the steps presented in the intro don't align perfectly with what is presented in the guide. There are a lot of smaller changes that are necessary. However, it was intended to be a general outline which highlights the key steps that are required in the migration process.

They do sort of align though. Removing Tomcat and adding Liberty are both performed in the POM. The section about changing the application startup process is teaching how to run from a traditional WAR deployment. Finally, package and deploy is covered by the `mvnbuild` and `mvncompile` template documents. Perhaps I should talk more explicitly about packaging, as this is done automatically by the build. 

> "Change the packaging type", "Add POM properties", "Add and modify dependencies" and "Add the Liberty Maven Plugin" sub headings may not be needed. Can be replaced with a sentence. ie, perhaps "First, you need to change the package to <packaging>liberty-assembly</packaging>."

If you feel strongly about this, then I remove them. However I feel like it is good for the structure of the guide. Otherwise you would just get `Modifying the POM` followed by a wall of text. 

> The related guide section is linked to an empty guide.

Any suggestions for related guides? I am not aware of any other guide like this that we have. I also would have thought that we have an algorithm that produces them - this is what most websites do, and it eliminates the need to update old guides to point to new guides that are related.

**Comment by chyt** [comment] 2018-07-05 13:39
> Self-referential language is sort of redundant/unnecessary because the user should assume that the contents of the guide they're reading apply to that guide. For example, I wouldn't say, "This book is a story about..." or "In this story...". Rather, I'd just start writing about what happens in the story. The reader should already know it's a story (about something). Same thing with instructions. You can just jump right in and start telling the user what to do instead of first telling them that they're looking at a guide and that these particular instructions concern this particular guide. Hope that helps! :)

@sishida I agree in general with what you are saying. I have changed the intro to only reference the Spring Boot guide once in the third person (saying `that guide`). I think it would also be redundant so refer to the guide by name, as I just did so in the previous sentence. 

Please see the changes at 77e3cd919c2e62ea73b5ea6f6703ab420d9e0ff2 and let me know if it is sufficient.

**Comment by sishida** [comment] 2018-07-05 13:44
@chyt Thanks for making edits! I have assigned this issue to Karen, who is the new Open Liberty ID focal.

@chirp1 Hi, Karen, Could you please take a look at the updates for this issue or assign it to another WAS ID writer? Thank you!

**Comment by evelinec** [comment] 2018-07-09 22:07
@chirp1 FYI, this guide is not ready for formal ID review yet. Feel free to comment on the questions. Thank you.

**Comment by evelinec** [comment] 2018-07-11 22:03
Had a chat with @chyt yesterday to sort out all of the issues raised above. Here're the new observations after the latest changes: 

- [x] There are 2 mentions of the Java 8 requirement statement. One is in "What you'll learn" and the other under "Running the application in embedded Tomcat". I think we agreed that the first is not needed. 

- [x] Finally, you will package and deploy the application to Open Liberty. => as we agreed to make change for the word "finally" here. 

- [x] Make these changes in the start folder. Navigate to the pom.xml file to modify the starter POM. => can be change to: Navigate to the `start` directory. You will modify the `pom.xml` file in several steps.

- [x] All subheadings under "Modifying the POM" need to start with a gerund. The subheadings would be really good to match with the steps described in the "What you'll learn".

**Comment by evelinec** [comment] 2018-07-16 21:37
No change for the following: 

- [ ] Within "What you'll learn", may be good to add what's the benefit of using Open Liberty or explain why using OL.

**Comment by evelinec** [comment] 2018-07-16 21:44
Need to discuss these points further: 

- [x] Java 8 requirement

- [x] Instruction for inserting code, ie, `No packaging type is specified in the starting project, so you’ll need to add <packaging>liberty-assembly</packaging> near the top of the POM.`

- [x] Still think the subheadings would be really good to match with the steps described in the "What you'll learn".

**Comment by evelinec** [comment] 2018-07-18 20:39
Follow up issues: 

- [x] The "include::finish/pom.xml" did not show up on the website. Perhaps the link is not correct.

- [x] Navigate to the start directory. You will modify the pom.xml file in several steps. => I'd recommend changing this section like the following. This way, it's clearer that the included pom.xml is the finished version. 

```
You will modify the `pom.xml` file in several steps. 
include::finish/pom.xml (make sure the link is correct)

Navigate to the `start` directory to begin. 
```

- [x] The following code snippet should be formatted the same way as in the "Adding POM properties" subsection. For example, show the code snippet to be added, and then show the finished code. Also remove the comment "". 

```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-thymeleaf</artifactId>
    <!-- Add this -->
    <exclusions>
        <exclusion>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-tomcat</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

- [x] Finally, replace the spring-boot-maven-plugin configuration with the liberty-maven-plugin configuration as shown below. => I think the words "as shown below" is not needed here.

**Comment by evelinec** [comment] 2018-07-19 19:26
The latest changes look good. Thanks

**Closed as completed** 2018-07-19 19:28 UTC
